services:
  - type: web
    name: prediction-markets-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /_health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: prediction-markets-db
          property: connectionString

databases:
  - name: prediction-markets-db
    plan: free
